// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file plugin/python.proto (package plugin, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GenerateRequest, GenerateResponse } from "./python_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service plugin.PythonService
 */
export const PythonService = {
  typeName: "plugin.PythonService",
  methods: {
    /**
     * @generated from rpc plugin.PythonService.Generate
     */
    generate: {
      name: "Generate",
      I: GenerateRequest,
      O: GenerateResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

