version: '3.6'
services:
  ctfg:
    image: ghcr.io/ctfg/ctfg@sha256:136b0b7af5b190326e090a01f50b62fe1025d13ce5bf80d69dac6235bc728f42
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
volumes:
  db:
