version: '3.6'
services:
  ctfg:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/db
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data/db
    labels:
      kompose.service.type: clusterip
      kompose.volume.type: persistentVolumeClaim
volumes:
  db:
