version: '3.6'
services:
  ctfg:
    image: ghcr.io/ctfg/ctfg@sha256:439fd10b079493d8699bbf5e84d3a8ec1c032f5852dbac9f2e245c969bcacc6e
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
volumes:
  db:
