version: '3.6'
services:
  ctfg:
    image: ghcr.io/ctfg/ctfg@sha256:a79fa593787303e70149a7f7eff2a781bfb4f1450749b917b8386a88b4cc294c
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
volumes:
  db:
