version: '3.6'
services:
  ctfg:
    image: ghcr.io/ctfg/ctfg@sha256:2dfed91df1f7c55a9819c67ae064bb81c9201146bd6a19b6abef94236471d757
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
volumes:
  db:
