version: '3.6'
services:
  ctfg:
    image: ghcr.io/ctfg/ctfg@sha256:bde419d087e64919454002b436c113d002914cc9b89f171b945b9da363403f7e
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
volumes:
  db:
