version: '3.6'
services:
  ctfg:
    image: ghcr.io/ctfg/ctfg@sha256:6de3776b2a0b4455aa4494683600eb2d1a007a59aa2f46a82018ac010ba76bd1
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
volumes:
  db:
