version: '3.6'
services:
  ctfg:
    image: ghcr.io/ctfg/ctfg@sha256:52e54bf24682b999dd709595830e028e45aff3639c00ded804ebc5eea56f83fd
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
volumes:
  db:
