version: '3.6'
services:
  ctfg:
    image: ghcr.io/ctfg/ctfg@sha256:06a46d93a50b19cefebe11a0087d2718764fcebc59957b5696b8e802496e1623
    restart: always
    ports:
      - 8000:8000
    environment:
      PORT: 8000
      DB_TYPE: "postgres"
      DB_DSN: "host=postgres user=postgres password=password sslmode=disable"
      CTFG_ADMIN_EMAIL: admin@admin.com
      CTFG_ADMIN_PASSWORD: password
    labels:
      kompose.service.type: clusterip
      kompose.image-pull-secret: "ghcr-pull-secret"
volumes:
  db:
