apiVersion: v1
kind: Pod
metadata:
  labels:
    application: shell-1
  name: shell-1
  namespace: shells
spec:
  containers:
  - env:
    - name: VNC_PW
      value: MrIhxjrh4Fkftmnl
    image: justluk/xfce-desktop
    imagePullPolicy: Always
    livenessProbe:
      initialDelaySeconds: 1
      tcpSocket:
        port: 5901
      timeoutSeconds: 1
    name: headless-vnc
    readinessProbe:
      httpGet:
        path: /
        port: 6901
        scheme: HTTP
      initialDelaySeconds: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 750m
        memory: 750Mi
      requests:
        cpu: 250m
        memory: 250Mi
  terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: shell-1
  name: shell-1-svc
  namespace: shells
spec:
  ports:
  - name: http-port-tcp
    port: 80
    protocol: TCP
    targetPort: 6901
  selector:
    application: shell-1
  type: ClusterIP
