FROM hasura/graphql-engine:v2.0.0-beta.2.cli-migrations-v3
# install editors and global config for interactive hasura-cli
RUN apt-get update && apt-get install -y nano vim; mkdir /.hasura; chmod 777 /.hasura
