// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cli

import (
	"github.com/urfave/cli/v2"
	"github.com/xctf-io/xctf/pkg/admin"
	"github.com/xctf-io/xctf/pkg/backend"
	"github.com/xctf-io/xctf/pkg/bucket"
	"github.com/xctf-io/xctf/pkg/chals"
	"github.com/xctf-io/xctf/pkg/config"
	"github.com/xctf-io/xctf/pkg/db"
	"github.com/xctf-io/xctf/pkg/http"
	"github.com/xctf-io/xctf/pkg/kubes"
	"github.com/xctf-io/xctf/pkg/log"
	"github.com/xctf-io/xctf/pkg/openai"
	"github.com/xctf-io/xctf/pkg/server"
)

// Injectors from wire.go:

func Wire() (*cli.App, error) {
	provider, err := config.New()
	if err != nil {
		return nil, err
	}
	logConfig, err := log.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	logLog := log.NewLog(logConfig)
	serverConfig, err := server.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	dbConfig, err := db.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	bucketConfig, err := bucket.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	service, err := db.New(dbConfig, bucketConfig)
	if err != nil {
		return nil, err
	}
	store, err := http.New(service)
	if err != nil {
		return nil, err
	}
	kubesConfig, err := kubes.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	openaiConfig, err := openai.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	kubesService, err := kubes.New(kubesConfig, openaiConfig)
	if err != nil {
		return nil, err
	}
	chalsConfig, err := chals.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	builder, err := bucket.NewBuilder(bucketConfig)
	if err != nil {
		return nil, err
	}
	pythonServiceClient, err := chals.NewPythonPlugin(chalsConfig)
	if err != nil {
		return nil, err
	}
	handler := chals.NewHandler(chalsConfig, service, builder, pythonServiceClient, store)
	agent, err := openai.NewAgent(openaiConfig)
	if err != nil {
		return nil, err
	}
	backendBackend := backend.NewBackend(service, store, handler, agent, builder, chalsConfig)
	adminAdmin := admin.NewAdmin(service, builder)
	httpHandler, err := server.New(serverConfig, store, kubesService, backendBackend, adminAdmin, builder, handler)
	if err != nil {
		return nil, err
	}
	app := New(logLog, serverConfig, httpHandler)
	return app, nil
}
