// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cli

import (
	"github.com/urfave/cli/v2"
	"github.com/xctf-io/xctf/pkg/admin"
	"github.com/xctf-io/xctf/pkg/backend"
	"github.com/xctf-io/xctf/pkg/config"
	"github.com/xctf-io/xctf/pkg/http"
	"github.com/xctf-io/xctf/pkg/kubes"
	"github.com/xctf-io/xctf/pkg/server"
)

// Injectors from wire.go:

func Wire() (*cli.App, error) {
	provider, err := config.New()
	if err != nil {
		return nil, err
	}
	serverConfig, err := server.NewConfig(provider)
	if err != nil {
		return nil, err
	}
	db := server.NewDB()
	store, err := http.New(db)
	if err != nil {
		return nil, err
	}
	service, err := kubes.NewService()
	if err != nil {
		return nil, err
	}
	backendBackend := backend.NewBackend(db, store)
	adminAdmin := admin.NewAdmin(db)
	handler := server.New(serverConfig, store, service, backendBackend, adminAdmin)
	app := New(handler)
	return app, nil
}
