name: cyber-forensics-platform
services:
- name: web
  source_dir: /client/src/cyber-forensics-platform
  github:
    repo: xctf-io/xctf
    branch: main
  build_command: npm install && npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: OPENAI_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_AND_BUILD_TIME
    type: SECRET
databases:
- name: cyber-forensics-db
  engine: PG
  version: "15"
  size: db-s-dev-database