// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file chalgen/chalgen.proto (package chalgen, syntax proto3)
/* eslint-disable */
// @ts-nocheck

/**
 * @generated from service chalgen.ChalgenService
 */
export const ChalgenService = {
  typeName: "chalgen.ChalgenService",
  methods: {
  }
} as const;

